sonar.projectKey=Netflix
sonar.projectName=Netflix
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts
sonar.exclusions=**/*.d.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/components/**,**/pages/**,**/providers/**,**/layouts/**,**/hoc/**
